### ISSUE TITLE
[JOSS REVIEW]

### ISSUE THREAD

**Issue by anotherjoshsmith** [msmexplorer/msmexplorer#77] opened 2017-03-09 23:34 UTC
_The following tasks should be completed for JOSS acceptance:_

__Installation:__
- [x] Support conda install with python 3.6. 
- [x] Specify version requirements (if applicable) for dependencies. The Fs-peptide notebook gets angry at pandas 0.16 (a few years behind the times) for the tICA cell. Alternatively, suggest that users update to most recent version for these dependencies if they are using an existing python 3.4 build.

__Example usage:__
- [x] Describe a possible use case for the chord diagram. It seems a bit disconnected from the rest of the tools, so adding an example (perhaps to some visualization of FS-peptide structure) could really tie things together.

__Community guidelines:__
- [x] Add a sentence to the "Development" section of your README directing potential contributors to the link you have already included.
- [x] Include a preferred method of contact for users seeking support.

__Version:__
- [x] Cut v1.0.0

**Comment by cxhernandez** [comment] 2017-03-10 00:39
Thanks for the review, @anotherjoshsmith! 


> Support conda install with python 3.6.

I think it should already be supported [under the omnia channel](https://anaconda.org/omnia/msmexplorer/files), but I've also been meaning to add msmexplorer to conda-forge as well.

As for the other items, I'll get started on a PR to address them.

**Comment by anotherjoshsmith** [comment] 2017-03-10 00:54
`conda install -c omnia msmexplorer` doesn't work for me on a fresh python 3.6 build on OSX, but everything installs fine with python 3.4. I'm having the same problem with msmbuilder on 3.6.

**Comment by Lnaden** [comment] 2017-03-10 01:21
The problem is that the `msmbuilder` was uploaded under the `rc` tag and not the `main` tag, so a standard install procedure will miss it. Let me tag the author of that package to see why its on the rc tag and see if I can get a solution for you.

**Comment by Lnaden** [comment] 2017-03-10 01:30
If you need a "right-now-right-now" solution, you can add the `-c omnia/label/rc` to your `conda install` and and it *should*(?) install

**Comment by cxhernandez** [comment] 2017-03-30 08:13
@anotherjoshsmith: Please review the changes made in #79, when you get a chance.

I updated the [chord diagram example](https://github.com/cxhernandez/msmexplorer/blob/6e7273d4ed5c33a921ebea12a4c79d01e905f9c0/examples/plot_chord.py) to show how it can be used to plot a hydrogen bonding network in Fs Peptide:

![image](https://cloud.githubusercontent.com/assets/5142365/24494138/1a36b552-14e6-11e7-9b26-6667685651e8.png)

**Comment by anotherjoshsmith** [comment] 2017-04-02 19:05
@cxhernandez Looks great! Chord diagram example is just what I had in mind and issues with python 3.6 installation seem to be fixed.

**Comment by anotherjoshsmith** [comment] 2017-04-02 19:11
@cxhernandez Ping me when you've merged successfully and I'll suggest @arokem set the publication wheel in motion.

**Comment by cxhernandez** [comment] 2017-04-04 16:59
@anotherjoshsmith: PR has been merged and v1.0.0 should be out in the wild.

**Closed** 2017-04-08 17:03 UTC
